"""
Just for fun, I did the first Advent 2017 challenge in Blockly (dumped to Python as well).  If you're curious,
go to https://blockly-demo.appspot.com/static/tests/playground.html and paste in the following XML
and click "import from XML".  And then be sad for me.

NOTE:  the actual Python code was GENERATED by Blockly -- I did NOT write that :P
However, I did test it since it can't actually be run on the Blockly site.

<xml xmlns="http://www.w3.org/1999/xhtml">
  <variables>
    <variable type="" id="=DKGQlCp{rLQ%(u3h}=!">x</variable>
    <variable type="" id=".Fu`NAKdM+[SS/2|7e_*">int</variable>
    <variable type="" id="`DUsqBEYrSc0AOGcw]HY">v1</variable>
    <variable type="" id="rHLv}hz2?~~F0.=cp__D">v2</variable>
    <variable type="" id="+w6La!k^HcJ+2nb1F*]G">text</variable>
    <variable type="" id="scMNDG%iZ^$Fv6WT3k5A">i</variable>
    <variable type="" id="MwL@mKVbF)G1bdLxqiWf">j</variable>
    <variable type="" id="9#ZWhCcKdBT2m}62![ST">pairs</variable>
    <variable type="" id="tAA?O#1{[R$zaY,W_Z;a">list</variable>
    <variable type="" id="Sar6-1g@z`tJnADqE~J.">res</variable>
    <variable type="" id="5){w6u^L-KL,_cJS:0}9">k</variable>
    <variable type="" id="}5n{KFinz)wy7}Exihqf">integers</variable>
    <variable type="" id="vd(Oc;BwVuFmz}?i^@{I">integerList</variable>
    <variable type="" id=":5#U[!v3T{BTF3BTr:VY">m</variable>
    <variable type="" id="]A:AxtM?^wh?D$|Xpsfy">n</variable>
    <variable type="" id="kn^18J_Auz5E{|%[,pv9">o</variable>
    <variable type="" id="G2JFo5W2q0`+Uo;H}AbD">p</variable>
  </variables>
  <block type="procedures_defreturn" id="!fJ4`%^|DYuuV$=P:m;b" x="-138" y="-837">
    <mutation>
      <arg name="x"></arg>
    </mutation>
    <field name="NAME">text2int</field>
    <comment pinned="false" h="80" w="160">Describe this function...</comment>
    <statement name="STACK">
      <block type="variables_set" id=")0)tpd.,z*u2k=,er3]/">
        <field name="VAR" id="}5n{KFinz)wy7}Exihqf" variabletype="">integers</field>
        <value name="VALUE">
          <block type="text" id="Zxw;LT/S}|C*5`@k~]mx">
            <field name="TEXT">0123456789</field>
          </block>
        </value>
        <next>
          <block type="variables_set" id="]pyj;Rzm^8e;3YqXF[p1">
            <field name="VAR" id="vd(Oc;BwVuFmz}?i^@{I" variabletype="">integerList</field>
            <value name="VALUE">
              <block type="lists_create_with" id="gcE]=`p8]!!ZS#Y.5(0d">
                <mutation items="0"></mutation>
              </block>
            </value>
            <next>
              <block type="controls_for" id=")goJUaJ[]3sc4uFZE`Tx">
                <field name="VAR" id="]A:AxtM?^wh?D$|Xpsfy" variabletype="">n</field>
                <value name="FROM">
                  <shadow type="math_number" id="Tj,hOg@v3qH_SK^uO)Ms">
                    <field name="NUM">0</field>
                  </shadow>
                </value>
                <value name="TO">
                  <shadow type="math_number" id="lfAmiLCP1WUwrBxM(SPo">
                    <field name="NUM">10</field>
                  </shadow>
                  <block type="math_arithmetic" id="^Ny|9$n62ougo4MEOW4a">
                    <field name="OP">MINUS</field>
                    <value name="A">
                      <shadow type="math_number" id="[AXIljDc5#E1zD_*~:]l">
                        <field name="NUM">1</field>
                      </shadow>
                      <block type="text_length" id="lp]xC-UI{(rzGhjTB5`w">
                        <value name="VALUE">
                          <shadow type="text" id="9[}XqI#bt2v+:4L_ozeU">
                            <field name="TEXT">abc</field>
                          </shadow>
                          <block type="variables_get" id="0(exZ+fHY~YIYK-Nrt,:">
                            <field name="VAR" id="}5n{KFinz)wy7}Exihqf" variabletype="">integers</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <value name="B">
                      <shadow type="math_number" id="]uRIf/g^F}+(^Pmex#ZU">
                        <field name="NUM">1</field>
                      </shadow>
                    </value>
                  </block>
                </value>
                <value name="BY">
                  <shadow type="math_number" id="5*#$oOf+gh`%rSVc$p^f">
                    <field name="NUM">1</field>
                  </shadow>
                </value>
                <statement name="DO">
                  <block type="lists_setIndex" id="_pt5Q~fQ:]Dbf!W_Sxg^">
                    <mutation at="false"></mutation>
                    <field name="MODE">INSERT</field>
                    <field name="WHERE">LAST</field>
                    <value name="LIST">
                      <block type="variables_get" id="$LD9H4cC+2Wn6Z5unT0.">
                        <field name="VAR" id="vd(Oc;BwVuFmz}?i^@{I" variabletype="">integerList</field>
                      </block>
                    </value>
                    <value name="TO">
                      <block type="lists_create_with" id="8;t_Dn.s@BZi]_GR3pzn">
                        <mutation items="2"></mutation>
                        <value name="ADD0">
                          <block type="text_charAt" id="}II)4B@~!E(E3Qs-~N):">
                            <mutation at="true"></mutation>
                            <field name="WHERE">FROM_START</field>
                            <value name="VALUE">
                              <block type="variables_get" id="~nBg$.Cv$u[@gyf6~o*8">
                                <field name="VAR" id="}5n{KFinz)wy7}Exihqf" variabletype="">integers</field>
                              </block>
                            </value>
                            <value name="AT">
                              <block type="math_arithmetic" id="g=0)N~},,I1d9T_9ADaH">
                                <field name="OP">ADD</field>
                                <value name="A">
                                  <shadow type="math_number" id="3mTY!6V4-pT2!2Zu?.Yq">
                                    <field name="NUM">1</field>
                                  </shadow>
                                  <block type="variables_get" id="8e32kBAf@G!Hee2`RH-#">
                                    <field name="VAR" id="]A:AxtM?^wh?D$|Xpsfy" variabletype="">n</field>
                                  </block>
                                </value>
                                <value name="B">
                                  <shadow type="math_number" id="7IkYP|Yn1L_11-,jO#,k">
                                    <field name="NUM">1</field>
                                  </shadow>
                                </value>
                              </block>
                            </value>
                          </block>
                        </value>
                        <value name="ADD1">
                          <block type="variables_get" id=",Q^oyCOOLwuvQIWyBEbJ">
                            <field name="VAR" id="]A:AxtM?^wh?D$|Xpsfy" variabletype="">n</field>
                          </block>
                        </value>
                      </block>
                    </value>
                  </block>
                </statement>
                <next>
                  <block type="controls_forEach" id="U[1~6f{Nzg6tH]}L=K?z">
                    <field name="VAR" id="kn^18J_Auz5E{|%[,pv9" variabletype="">o</field>
                    <value name="LIST">
                      <block type="variables_get" id="fn9pF2$q(FkQ6.^*O+E#">
                        <field name="VAR" id="vd(Oc;BwVuFmz}?i^@{I" variabletype="">integerList</field>
                      </block>
                    </value>
                    <statement name="DO">
                      <block type="procedures_ifreturn" id="LY%FAiX5+iY6ziiCeFMi">
                        <mutation value="1"></mutation>
                        <value name="CONDITION">
                          <block type="logic_compare" id="2_%cJ!%A(ML[9T}Z$d~C">
                            <field name="OP">EQ</field>
                            <value name="A">
                              <block type="variables_get" id="THT|oN@a:w.f)}4`^2x`">
                                <field name="VAR" id="=DKGQlCp{rLQ%(u3h}=!" variabletype="">x</field>
                              </block>
                            </value>
                            <value name="B">
                              <block type="lists_getIndex" id="_yIf(_?CTTj,t(WS`]tc">
                                <mutation statement="false" at="false"></mutation>
                                <field name="MODE">GET</field>
                                <field name="WHERE">FIRST</field>
                                <value name="VALUE">
                                  <block type="variables_get" id="%u9+4y)SU#3H5J3yi@k,">
                                    <field name="VAR" id="kn^18J_Auz5E{|%[,pv9" variabletype="">o</field>
                                  </block>
                                </value>
                              </block>
                            </value>
                          </block>
                        </value>
                        <value name="VALUE">
                          <block type="lists_getIndex" id="|}/2{dg9_?{G6,smrx0V">
                            <mutation statement="false" at="false"></mutation>
                            <field name="MODE">GET</field>
                            <field name="WHERE">LAST</field>
                            <value name="VALUE">
                              <block type="variables_get" id="(/cGOP!tWomSzdR:T,hO">
                                <field name="VAR" id="kn^18J_Auz5E{|%[,pv9" variabletype="">o</field>
                              </block>
                            </value>
                          </block>
                        </value>
                      </block>
                    </statement>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="procedures_defreturn" id="W+fr*^KSYp{vc84ymnUZ" x="-138" y="-462">
    <mutation>
      <arg name="int"></arg>
    </mutation>
    <field name="NAME">captcha</field>
    <comment pinned="false" h="80" w="160">Describe this function...</comment>
    <statement name="STACK">
      <block type="variables_set" id="I;-1X./k/DKUh:8t}=],">
        <field name="VAR" id="`DUsqBEYrSc0AOGcw]HY" variabletype="">v1</field>
        <value name="VALUE">
          <block type="text_getSubstring" id=".I$3Y%M10}*XT(iLKJha">
            <mutation at1="false" at2="true"></mutation>
            <field name="WHERE1">FIRST</field>
            <field name="WHERE2">FROM_END</field>
            <value name="STRING">
              <block type="variables_get" id="Fs,_usANiqsK[tzto9/o">
                <field name="VAR" id=".Fu`NAKdM+[SS/2|7e_*" variabletype="">int</field>
              </block>
            </value>
            <value name="AT2">
              <block type="math_number" id="]eWn$-+`o$Y{1m]U/6ST">
                <field name="NUM">2</field>
              </block>
            </value>
          </block>
        </value>
        <next>
          <block type="variables_set" id="kEtdSvq)5/5o(N/=E+Kh">
            <field name="VAR" id="rHLv}hz2?~~F0.=cp__D" variabletype="">v2</field>
            <value name="VALUE">
              <block type="text_getSubstring" id="8C-~PV[!qQ~P,36jgO/M">
                <mutation at1="true" at2="false"></mutation>
                <field name="WHERE1">FROM_START</field>
                <field name="WHERE2">LAST</field>
                <value name="STRING">
                  <block type="variables_get" id="24bENf9N,nMC,,j.?;3s">
                    <field name="VAR" id=".Fu`NAKdM+[SS/2|7e_*" variabletype="">int</field>
                  </block>
                </value>
                <value name="AT1">
                  <block type="math_number" id="Lt}Iy9TJ/XhWsS-6~:S?">
                    <field name="NUM">2</field>
                  </block>
                </value>
              </block>
            </value>
            <next>
              <block type="variables_set" id="r*JW@8xmHc=kYqz?-#}8">
                <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                <value name="VALUE">
                  <block type="lists_create_with" id="H0T}2m.LUc-s(KmG$?VV">
                    <mutation items="0"></mutation>
                  </block>
                </value>
                <next>
                  <block type="controls_forEach" id="k5%%419.On$F~(!04^q+">
                    <field name="VAR" id="scMNDG%iZ^$Fv6WT3k5A" variabletype="">i</field>
                    <value name="LIST">
                      <block type="variables_get" id="w~%q`~[_nH*T-e|qfXd:">
                        <field name="VAR" id="`DUsqBEYrSc0AOGcw]HY" variabletype="">v1</field>
                      </block>
                    </value>
                    <statement name="DO">
                      <block type="lists_setIndex" id="n-um,mtXY[7.vPMn_H||">
                        <mutation at="false"></mutation>
                        <field name="MODE">INSERT</field>
                        <field name="WHERE">LAST</field>
                        <value name="LIST">
                          <block type="variables_get" id="yB^/%Px_MP;oI)~sQqY5">
                            <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                          </block>
                        </value>
                        <value name="TO">
                          <block type="lists_create_with" id="A49}R=[gH#nEv[R47u@v">
                            <mutation items="2"></mutation>
                            <value name="ADD0">
                              <block type="variables_get" id="wFNLG!m]v,lk2sv:vJWt">
                                <field name="VAR" id="scMNDG%iZ^$Fv6WT3k5A" variabletype="">i</field>
                              </block>
                            </value>
                          </block>
                        </value>
                      </block>
                    </statement>
                    <next>
                      <block type="controls_for" id="3,_cfNmNSC%:_d}NXR?c">
                        <field name="VAR" id="G2JFo5W2q0`+Uo;H}AbD" variabletype="">p</field>
                        <value name="FROM">
                          <shadow type="math_number" id="9Y%a!|8QQ]%Q_-yy3$*7">
                            <field name="NUM">0</field>
                          </shadow>
                        </value>
                        <value name="TO">
                          <shadow type="math_number" id="lfAmiLCP1WUwrBxM(SPo">
                            <field name="NUM">10</field>
                          </shadow>
                          <block type="math_arithmetic" id="GG7axJLJ2$t=6LtvGe.T">
                            <field name="OP">MINUS</field>
                            <value name="A">
                              <shadow type="math_number" id="[AXIljDc5#E1zD_*~:]l">
                                <field name="NUM">1</field>
                              </shadow>
                              <block type="text_length" id="x/nRj.6NdS;XAD!nHyV_">
                                <value name="VALUE">
                                  <shadow type="text" id="9[}XqI#bt2v+:4L_ozeU">
                                    <field name="TEXT">abc</field>
                                  </shadow>
                                  <block type="variables_get" id="J^eAE0n:U_@v8|(3=$UO">
                                    <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                                  </block>
                                </value>
                              </block>
                            </value>
                            <value name="B">
                              <shadow type="math_number" id="j=rvb*t$dg-370ivvT|?">
                                <field name="NUM">1</field>
                              </shadow>
                            </value>
                          </block>
                        </value>
                        <value name="BY">
                          <shadow type="math_number" id="N*k`V*b+jlyE6lzmK]lm">
                            <field name="NUM">1</field>
                          </shadow>
                        </value>
                        <statement name="DO">
                          <block type="lists_setIndex" id="7)]cOxjZ|}T_*eZ/@B+k">
                            <mutation at="true"></mutation>
                            <field name="MODE">SET</field>
                            <field name="WHERE">FROM_START</field>
                            <value name="LIST">
                              <block type="variables_get" id="k*5N[G*a2lNHj)8DqMy8">
                                <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                              </block>
                            </value>
                            <value name="AT">
                              <block type="variables_get" id="wb,%^I|(=4-3pGJW6z*?">
                                <field name="VAR" id="G2JFo5W2q0`+Uo;H}AbD" variabletype="">p</field>
                              </block>
                            </value>
                            <value name="TO">
                              <block type="lists_create_with" id="qbuRz-QC.5CRRJ28?vl#">
                                <mutation items="2"></mutation>
                                <value name="ADD0">
                                  <block type="lists_getIndex" id="De,roShxCJ+bo|xIqw?r">
                                    <mutation statement="false" at="false"></mutation>
                                    <field name="MODE">GET</field>
                                    <field name="WHERE">FIRST</field>
                                    <value name="VALUE">
                                      <block type="lists_getIndex" id="lkyZ)ASK4eJ4VQFBc6W{">
                                        <mutation statement="false" at="true"></mutation>
                                        <field name="MODE">GET</field>
                                        <field name="WHERE">FROM_START</field>
                                        <value name="VALUE">
                                          <block type="variables_get" id=")H|._#i~o/AQ9O*Y-@Ub">
                                            <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                                          </block>
                                        </value>
                                        <value name="AT">
                                          <block type="variables_get" id="iv!XOxK-qxO5vv%Y(ozi">
                                            <field name="VAR" id="G2JFo5W2q0`+Uo;H}AbD" variabletype="">p</field>
                                          </block>
                                        </value>
                                      </block>
                                    </value>
                                  </block>
                                </value>
                                <value name="ADD1">
                                  <block type="lists_getIndex" id="t:?c#9=3?hBncE;y2Zcw">
                                    <mutation statement="false" at="true"></mutation>
                                    <field name="MODE">GET</field>
                                    <field name="WHERE">FROM_START</field>
                                    <value name="VALUE">
                                      <block type="variables_get" id="G?^2gG{G/]qAwH=pllbU">
                                        <field name="VAR" id="rHLv}hz2?~~F0.=cp__D" variabletype="">v2</field>
                                      </block>
                                    </value>
                                    <value name="AT">
                                      <block type="variables_get" id="LR#I~XVj@7Vc+0@@C2ZC">
                                        <field name="VAR" id="G2JFo5W2q0`+Uo;H}AbD" variabletype="">p</field>
                                      </block>
                                    </value>
                                  </block>
                                </value>
                              </block>
                            </value>
                          </block>
                        </statement>
                        <next>
                          <block type="lists_setIndex" id="qNv@M!C5cdEN3mHy_6+U">
                            <mutation at="false"></mutation>
                            <field name="MODE">INSERT</field>
                            <field name="WHERE">LAST</field>
                            <value name="LIST">
                              <block type="variables_get" id="!gb7.{huBMXGzz{Tn{6Y">
                                <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                              </block>
                            </value>
                            <value name="TO">
                              <block type="lists_create_with" id="]Kbx|[]%KH]lf3ifx8MY">
                                <mutation items="2"></mutation>
                                <value name="ADD0">
                                  <block type="text_charAt" id="kp[KHTunx_x*Q:xw_;1}">
                                    <mutation at="false"></mutation>
                                    <field name="WHERE">LAST</field>
                                    <value name="VALUE">
                                      <block type="variables_get" id="lysL#i^bZCW(TEy=A9/.">
                                        <field name="VAR" id=".Fu`NAKdM+[SS/2|7e_*" variabletype="">int</field>
                                      </block>
                                    </value>
                                  </block>
                                </value>
                                <value name="ADD1">
                                  <block type="text_charAt" id="X`i[3,c_.WP/F{Bw#0@4">
                                    <mutation at="false"></mutation>
                                    <field name="WHERE">FIRST</field>
                                    <value name="VALUE">
                                      <block type="variables_get" id=",E{h4ngHJN=4^4/U:R.^">
                                        <field name="VAR" id=".Fu`NAKdM+[SS/2|7e_*" variabletype="">int</field>
                                      </block>
                                    </value>
                                  </block>
                                </value>
                              </block>
                            </value>
                            <next>
                              <block type="variables_set" id="b?uV2-+wVj!jiPankR/`">
                                <field name="VAR" id="Sar6-1g@z`tJnADqE~J." variabletype="">res</field>
                                <value name="VALUE">
                                  <block type="math_number" id="lc.8NBTN)JmrggM89@S3">
                                    <field name="NUM">0</field>
                                  </block>
                                </value>
                                <next>
                                  <block type="controls_forEach" id="~6PXr1V5w+2}Zyq.7(E.">
                                    <field name="VAR" id="5){w6u^L-KL,_cJS:0}9" variabletype="">k</field>
                                    <value name="LIST">
                                      <block type="variables_get" id="=KbzkypQc8Mc~@S$]7d%">
                                        <field name="VAR" id="9#ZWhCcKdBT2m}62![ST" variabletype="">pairs</field>
                                      </block>
                                    </value>
                                    <statement name="DO">
                                      <block type="controls_if" id="4v$NLvp5Eb5GfZgNN=Mc">
                                        <value name="IF0">
                                          <block type="logic_compare" id="@D/Sq,K@8C~%oVhYP;^i">
                                            <field name="OP">EQ</field>
                                            <value name="A">
                                              <block type="lists_getIndex" id="R2QoXQ*fS06(OH|sH#sj">
                                                <mutation statement="false" at="true"></mutation>
                                                <field name="MODE">GET</field>
                                                <field name="WHERE">FROM_START</field>
                                                <value name="VALUE">
                                                  <block type="variables_get" id="IZ^vm*i70ov.?cU.,`yI">
                                                    <field name="VAR" id="5){w6u^L-KL,_cJS:0}9" variabletype="">k</field>
                                                  </block>
                                                </value>
                                                <value name="AT">
                                                  <block type="math_number" id="6ucIA.F9P`g-dn-lkx6p">
                                                    <field name="NUM">0</field>
                                                  </block>
                                                </value>
                                              </block>
                                            </value>
                                            <value name="B">
                                              <block type="lists_getIndex" id="o+}}TtcaiK@Mh(dya,wc">
                                                <mutation statement="false" at="true"></mutation>
                                                <field name="MODE">GET</field>
                                                <field name="WHERE">FROM_START</field>
                                                <value name="VALUE">
                                                  <block type="variables_get" id="%Sr8UjrdLmb2teo8A=P{">
                                                    <field name="VAR" id="5){w6u^L-KL,_cJS:0}9" variabletype="">k</field>
                                                  </block>
                                                </value>
                                                <value name="AT">
                                                  <block type="math_number" id="l^JD;rJfr}MrG!CRO=nP">
                                                    <field name="NUM">1</field>
                                                  </block>
                                                </value>
                                              </block>
                                            </value>
                                          </block>
                                        </value>
                                        <statement name="DO0">
                                          <block type="variables_set" id="eGV~x`Ka|Oa,V#CyvPgv">
                                            <field name="VAR" id="Sar6-1g@z`tJnADqE~J." variabletype="">res</field>
                                            <value name="VALUE">
                                              <block type="math_arithmetic" id="wz`uW27|7t(7ezlj=1s3">
                                                <field name="OP">ADD</field>
                                                <value name="A">
                                                  <shadow type="math_number" id="Q79QZH#y2$(j-8CR9cQ|">
                                                    <field name="NUM">1</field>
                                                  </shadow>
                                                  <block type="variables_get" id="R@fXHx%a-X}?+k@x)0c3">
                                                    <field name="VAR" id="Sar6-1g@z`tJnADqE~J." variabletype="">res</field>
                                                  </block>
                                                </value>
                                                <value name="B">
                                                  <shadow type="math_number" id="p.bdSvpe1n)`TEY1LmIH">
                                                    <field name="NUM">1</field>
                                                  </shadow>
                                                  <block type="procedures_callreturn" id="F%NRNk(+VH},9|lZ%64a">
                                                    <mutation name="text2int">
                                                      <arg name="x"></arg>
                                                    </mutation>
                                                    <value name="ARG0">
                                                      <block type="lists_getIndex" id="o1C`X3RW9y|OFi_bBu4V">
                                                        <mutation statement="false" at="true"></mutation>
                                                        <field name="MODE">GET</field>
                                                        <field name="WHERE">FROM_START</field>
                                                        <value name="VALUE">
                                                          <block type="variables_get" id=":L_f%[X[,t3xP5e7+cva">
                                                            <field name="VAR" id="5){w6u^L-KL,_cJS:0}9" variabletype="">k</field>
                                                          </block>
                                                        </value>
                                                        <value name="AT">
                                                          <block type="math_number" id="O8}u^DrlGT6OBZ-J%YYZ">
                                                            <field name="NUM">1</field>
                                                          </block>
                                                        </value>
                                                      </block>
                                                    </value>
                                                  </block>
                                                </value>
                                              </block>
                                            </value>
                                          </block>
                                        </statement>
                                      </block>
                                    </statement>
                                  </block>
                                </next>
                              </block>
                            </next>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
    <value name="RETURN">
      <block type="variables_get" id="}e^czIZ2L$p`-jc~9=.A">
        <field name="VAR" id="Sar6-1g@z`tJnADqE~J." variabletype="">res</field>
      </block>
    </value>
  </block>
  <block type="procedures_defreturn" id="My;QS`4CazKQ4Czx8yiD" x="-137" y="288">
    <field name="NAME">test</field>
    <comment pinned="false" h="80" w="160">Describe this function...</comment>
    <statement name="STACK">
      <block type="procedures_ifreturn" id="siO0xg+hj=ylu0_m^}c1">
        <mutation value="1"></mutation>
        <value name="CONDITION">
          <block type="logic_compare" id="`D-(Y]Prg_GUeHiPesPQ">
            <field name="OP">NEQ</field>
            <value name="A">
              <block type="procedures_callreturn" id="Jj]d^l%$X5/jZevJ@[.B">
                <mutation name="captcha">
                  <arg name="int"></arg>
                </mutation>
                <value name="ARG0">
                  <block type="text" id="WyYJ_)jARAl!v3ad6dF5">
                    <field name="TEXT">1111</field>
                  </block>
                </value>
              </block>
            </value>
            <value name="B">
              <block type="math_number" id="7z`j^iiMo7i%mXU;8Iq,">
                <field name="NUM">4</field>
              </block>
            </value>
          </block>
        </value>
        <value name="VALUE">
          <block type="logic_boolean" id="Gg~L/}?iLWw?x*sdVW-W">
            <field name="BOOL">FALSE</field>
          </block>
        </value>
        <next>
          <block type="procedures_ifreturn" id="gso}7@N|`@kMyyoPr!E#">
            <mutation value="1"></mutation>
            <value name="CONDITION">
              <block type="logic_compare" id=")FCY9w=e.pY#=HK==osG">
                <field name="OP">NEQ</field>
                <value name="A">
                  <block type="procedures_callreturn" id="4)U{0NyyRBi6yPPHp^35">
                    <mutation name="captcha">
                      <arg name="int"></arg>
                    </mutation>
                    <value name="ARG0">
                      <block type="text" id="Jz@:J2$kYPH.Zl;0(bJ+">
                        <field name="TEXT">1234</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="B">
                  <block type="math_number" id="sRzt^[b()kQ7/K[zG9Y(">
                    <field name="NUM">0</field>
                  </block>
                </value>
              </block>
            </value>
            <value name="VALUE">
              <block type="logic_boolean" id="Ouk~epDV1an2OOwyoo8l">
                <field name="BOOL">FALSE</field>
              </block>
            </value>
            <next>
              <block type="procedures_ifreturn" id="yKi#mrc;yd$;Fq1U].;*">
                <mutation value="1"></mutation>
                <value name="CONDITION">
                  <block type="logic_compare" id="1A2hI5$xe[Hze+S:EBsf">
                    <field name="OP">NEQ</field>
                    <value name="A">
                      <block type="procedures_callreturn" id="/GHp9p;}dwR^dFPk[R2e">
                        <mutation name="captcha">
                          <arg name="int"></arg>
                        </mutation>
                        <value name="ARG0">
                          <block type="text" id="2+it59}`*gQssg[U#%bM">
                            <field name="TEXT">1122</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <value name="B">
                      <block type="math_number" id=";6.AWIeApXLX;[I}n(:m">
                        <field name="NUM">3</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="VALUE">
                  <block type="logic_boolean" id="?ez|Rh!EeLik,mkmd+4{">
                    <field name="BOOL">FALSE</field>
                  </block>
                </value>
                <next>
                  <block type="procedures_ifreturn" id=";An*C#(zrPK@SARe+otl">
                    <mutation value="1"></mutation>
                    <value name="CONDITION">
                      <block type="logic_compare" id="Bt}s!HP,2_t#FJ|R)aXQ">
                        <field name="OP">NEQ</field>
                        <value name="A">
                          <block type="procedures_callreturn" id="gn[M;X[tr.f%s.xYY%GF">
                            <mutation name="captcha">
                              <arg name="int"></arg>
                            </mutation>
                            <value name="ARG0">
                              <block type="text" id="U#VoJXTmu}-+a`.4Z`Hl">
                                <field name="TEXT">91212129</field>
                              </block>
                            </value>
                          </block>
                        </value>
                        <value name="B">
                          <block type="math_number" id="BA]Co~PE$CfIyYD/fc^|">
                            <field name="NUM">9</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <value name="VALUE">
                      <block type="logic_boolean" id="XBd%sCFXnt[4:RZ}!b|Y">
                        <field name="BOOL">FALSE</field>
                      </block>
                    </value>
                    <next>
                      <block type="procedures_ifreturn" id="pUcG*7X)u$x3n}0sr|:`">
                        <mutation value="1"></mutation>
                        <value name="CONDITION">
                          <block type="logic_compare" id="L3*5zHg^Brh@FdNwPi)m">
                            <field name="OP">NEQ</field>
                            <value name="A">
                              <block type="procedures_callreturn" id="+NU=IopG6$tIZk2}D+=|">
                                <mutation name="captcha">
                                  <arg name="int"></arg>
                                </mutation>
                                <value name="ARG0">
                                  <block type="text" id="i7wKvUAzsK|/1y1XshJj">
                                    <field name="TEXT">31813174349235972159811869755166343882958376474278437681632495222499211488649543755655138842553867246131245462881756862736922925752647341673342756514856663979496747158241792857625471323535183222497949751644488277317173496124473893452425118133645984488759128897146498831373795721661696492622276282881218371273973538163779782435211491196616375135472517935481964439956844536136823757764494967297251545389464472794474447941564778733926532741752757865243946976266426548341889873514383464142659425122786667399143335772174973128383869893325977319651839516694295534146668728822393452626321892357192574444856264721585365164945647254645264693957898373214897848424966266582991272496771159583715456714645585576641458358326521858518319315233857473695712238323787254556597566461188452279853766184333696344395818615215846348586541164194624371353556812548945447432787795489443312941687221314432694115847863129826532628228386894683392352799514942665396273726821936346663485499159141368443782475714679953213388375939519711591262489869326145476958378464652451441434846382474578535468433514121336844727988128998543975147649823215332929623574231738442281161294838499441799996857746549441142859199799125595761724782225452394593514388571187279266291364278184761833324476838939898258225748562345853633364314923186685534864178665214135631494876474186833392929124337161222959459117554238429216916532175247326391321525832362274683763488347654497889261543959591212539851835354335598844669618391876623638137926893582131945361264841733341247646125278489995838369127582438419889922365596554237153412394494932582424222479798382932335239274297663365164912953364777876187522324991837775492621675953397843833247525599771974555545348388871578347332456586949283657613841414576976542343934911424716613479249893113961925713317644349946444271959375981158445151659431844142242547191181944395897963146947935463718145169266129118413523541222444997678726644615185324461293228124456118853885552279849917342474792984425629248492847827653133583215539325866881662159421987315186914769478947389188382383546881622246793781846254253759714573354544997853153798862436887889318646643359555663135476261863</field>
                                  </block>
                                </value>
                              </block>
                            </value>
                            <value name="B">
                              <block type="math_number" id="?B:;(M6)`Eej90AMcjur">
                                <field name="NUM">1203</field>
                              </block>
                            </value>
                          </block>
                        </value>
                        <value name="VALUE">
                          <block type="logic_boolean" id="2]!}9n1K_]KvMvZ%*x@A">
                            <field name="BOOL">FALSE</field>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
    <value name="RETURN">
      <block type="logic_boolean" id="g2$*07afKVLWv2~Q/yl)">
        <field name="BOOL">TRUE</field>
      </block>
    </value>
  </block>
  <block type="text_print" id="JH(?;e0@[#]T(]?s-4vK" x="-137" y="463">
    <value name="TEXT">
      <shadow type="text" id="he0#SGW4eO/an6L!Z[P6">
        <field name="TEXT">abc</field>
      </shadow>
      <block type="procedures_callreturn" id="s4fRmwGsMZ!o0gB#b4c-">
        <mutation name="test"></mutation>
      </block>
    </value>
  </block>
</xml>
"""



x = None
int2 = None
v1 = None
v2 = None
text = None
i = None
j = None
pairs = None
list2 = None
res = None
k = None
integers = None
integerList = None
m = None
n = None
o = None
p = None

def upRange(start, stop, step):
  while start <= stop:
    yield start
    start += abs(step)

def downRange(start, stop, step):
  while start >= stop:
    yield start
    start -= abs(step)

"""Describe this function...
"""
def text2int(x):
  global int2, v1, v2, text, i, j, pairs, list2, res, k, integers, integerList, m, n, o, p
  integers = '0123456789'
  integerList = []
  n_end = float(len(integers) - 1)
  for n in (0 <= n_end) and upRange(0, n_end, 1) or downRange(0, n_end, 1):
    integerList.append([integers[int((n + 1) - 1)], n])
  for o in integerList:
    if x == o[0]:
      return o[-1]

"""Describe this function...
"""
def captcha(int2):
  global x, v1, v2, text, i, j, pairs, list2, res, k, integers, integerList, m, n, o, p
  v1 = int2[ : -1]
  v2 = int2[1 : ]
  pairs = []
  for i in v1:
    pairs.append([i, None])
  p_end = float(len(pairs) - 1)
  for p in (0 <= p_end) and upRange(0, p_end, 1) or downRange(0, p_end, 1):
    pairs[int(p - 1)] = [pairs[int(p - 1)][0], v2[int(p - 1)]]
  pairs.append([int2[-1], int2[0]])
  res = 0
  for k in pairs:
    if k[-1] == k[0]:
      res = res + text2int(k[0])
  return res

"""Describe this function...
"""
def test():
  global x, int2, v1, v2, text, i, j, pairs, list2, res, k, integers, integerList, m, n, o, p
  if captcha('1111') != 4:
    return False
  if captcha('1234') != 0:
    return False
  if captcha('1122') != 3:
    return False
  if captcha('91212129') != 9:
    return False
  if captcha('31813174349235972159811869755166343882958376474278437681632495222499211488649543755655138842553867246131245462881756862736922925752647341673342756514856663979496747158241792857625471323535183222497949751644488277317173496124473893452425118133645984488759128897146498831373795721661696492622276282881218371273973538163779782435211491196616375135472517935481964439956844536136823757764494967297251545389464472794474447941564778733926532741752757865243946976266426548341889873514383464142659425122786667399143335772174973128383869893325977319651839516694295534146668728822393452626321892357192574444856264721585365164945647254645264693957898373214897848424966266582991272496771159583715456714645585576641458358326521858518319315233857473695712238323787254556597566461188452279853766184333696344395818615215846348586541164194624371353556812548945447432787795489443312941687221314432694115847863129826532628228386894683392352799514942665396273726821936346663485499159141368443782475714679953213388375939519711591262489869326145476958378464652451441434846382474578535468433514121336844727988128998543975147649823215332929623574231738442281161294838499441799996857746549441142859199799125595761724782225452394593514388571187279266291364278184761833324476838939898258225748562345853633364314923186685534864178665214135631494876474186833392929124337161222959459117554238429216916532175247326391321525832362274683763488347654497889261543959591212539851835354335598844669618391876623638137926893582131945361264841733341247646125278489995838369127582438419889922365596554237153412394494932582424222479798382932335239274297663365164912953364777876187522324991837775492621675953397843833247525599771974555545348388871578347332456586949283657613841414576976542343934911424716613479249893113961925713317644349946444271959375981158445151659431844142242547191181944395897963146947935463718145169266129118413523541222444997678726644615185324461293228124456118853885552279849917342474792984425629248492847827653133583215539325866881662159421987315186914769478947389188382383546881622246793781846254253759714573354544997853153798862436887889318646643359555663135476261863') != 1203:
    return False
  return True


print(test())
