;Even Fibonacci numbers
;Problem 2
;
;Each new term in the Fibonacci sequence is generated by adding
; the previous two terms. By starting with 1 and 2,
; the first 10 terms will be:
;
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
;By considering the terms in the Fibonacci sequence whose values
; do not exceed four million, find the sum of the even-valued terms.
;
(ns clojure-work.project-euler.pe2)

(defn fib*
  ([] (fib* 1 1))
  ([x y] (cons x (lazy-seq (fib* y (+ x y))))))

(defn main []
  "4613732"
  (println (reduce + (filter (fn [x] (#(= 0 (mod x 2))))
                             (take-while #(< % 4000000) (fib*))))))

(main)